name: Server Code style (prettier, lint)

on:
  push:
    branches: [develop, main]
  pull_request:
    branches: [develop, main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js and npm
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci
        working-directory: server

      - name: Debug environment
        run: |
          echo "Node.js version: $(node --version)"
          echo "npm version: $(npm --version)"
          npm list --depth=0
        working-directory: server

      - name: Run code style check
        run: npm run code-style-check
        working-directory: server
